### Sign Up
POST http://localhost:5000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "12345678",
    "username": "test3"
}

### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
}

### Current User
GET http://localhost:5000/api/auth/current HTTP/1.1

### Logout
POST http://localhost:5000/api/auth/logout HTTP/1.1

### Get Posts
GET http://localhost:5000/api/posts 


### Create Post
POST http://localhost:5000/api/posts HTTP/1.1
Content-Type: application/json

{
    "url": "https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    "caption": "Beautiful"
}